Caravan UI facelift
caravan-bitcoin/caravan pull request #142
Opened 2024-10-15 02:17 UTC by jbrauck-unchained

I'll add a better description tomorrow. Implements pieces from SoB designs.

2025-05-01 04:39 UTC, Legend101Zz commented
Hi @jbrauck-unchained ! This looks really cool—just came across it and love how the new UI highlights so many awesome features we already have in Caravan. I didn’t even realize the test suite feature existed before—super neat! Just wondering if you might need any help getting this merged? Happy to pitch in if I can.

Also, just an idea (feel free to ignore 😅)—maybe a fun little loading animation with the Caravan logo actually moving like a caravan could be a nice touch?

Something like this ... 

https://github.com/user-attachments/assets/79472bb8-40f6-40a8-bf6b-3654e41f372f

2025-05-08 00:25 UTC, jbrauck-unchained commented
Thanks for checking in on this @Legend101Zz. We had been waiting on some review of the actual copy we used in this work. The original design from SoB last year had a lot of AI generated language and we just want to make sure what content we are writing is actually correct.

I am able to do this part myself and would just love your review and approval after I get those changes in. Thank you!

2025-05-08 18:29 UTC, jbrauck-unchained commented
Shoutout @abbi4code for the help with that latest bug. What a relief!

2025-05-10 00:44 UTC, jbrauck-unchained commented
@Legend101Zz ready for review/merge

2025-05-10 06:57 UTC, Legend101Zz commented
Great @jbrauck-unchained throwing in some reviews now :)

2025-05-10 09:54 UTC, Legend101Zz requested changes
@jbrauck-unchained Thanks for the fantastic PR — really excited to see this live on the production site soon! I’ve left a few review comments for you to check out. Also, I think the changeset might be missing from the PR — would this count as a minor version bump?

2025-05-10 09:54 UTC, Legend101Zz commented on apps/coordinator/src/components/App.tsx
> +            width: 300,
ahh also as the condition `location.pathname === "/"` is used multiple times...

maybe a nit like :

```jsx
  const showDrawer = location.pathname !== "/";
  ```

2025-05-10 09:54 UTC, Legend101Zz commented on apps/coordinator/src/components/App.tsx
> +          marginLeft: location.pathname === "/" ? 0 : `300px`,
so this would look like :

```jsx
    marginLeft: !showDrawer ?  0 : DRAWER_WIDTH 
```

2025-05-10 09:54 UTC, Legend101Zz commented on apps/coordinator/src/components/App.tsx
> +        <Container maxWidth={false} disableGutters sx={{ maxWidth: "100%" }}>
---

So what I’m noticing is:

* `maxWidth={false}` disables the default responsive behavior of MUI’s `Container` component — so it stretches full-width.
* `disableGutters` removes the default horizontal padding (`theme.spacing(2)`, usually 16px).
* And then `sx={{ maxWidth: "100%" }}` explicitly sets the `max-width` to 100%.

That last bit kind of overlaps with what `maxWidth={false}` already does — so it ends up being redundant.

At that point, we’re basically just using `Container` like a plain `div` or `Box`, so maybe it’s cleaner and more intentional to just use one of those directly instead?

Let me know if you think otherwise, just thought I’d flag it!

2025-05-10 09:54 UTC, Legend101Zz commented on apps/coordinator/src/components/LandingNav.tsx
> +const useStyles = makeStyles(() =>
The styles are taking up more than half the component. Can we Create a separate file for them `LandingNav.styles.ts` ??

2025-05-10 09:54 UTC, Legend101Zz commented on apps/coordinator/src/components/LandingPage.tsx
> +const useStyles = makeStyles(() =>
same here can we move them to a seperate style file ?

2025-05-10 09:54 UTC, Legend101Zz commented on apps/coordinator/src/components/LandingPage.tsx
> +          <h4 className={classes.footerTitle}>Resources</h4>
---

Just a quick UX-related question — as a user, I initially couldn’t distinguish between the footer title and the actual footer text. At first glance, it looked like the links were missing entirely.

Would it be possible to create a clearer visual distinction between the two — maybe through stronger font weight, different color, or slight size variation? I think that would really help with readability and reduce any confusion.

2025-05-13 00:11 UTC, jbrauck-unchained commented on apps/coordinator/public/images/landing/caravan-balance.png
I will replace with all webps. Not sure how to run benchmark tests though and so would love for you to test again to check for improvement

2025-05-13 00:29 UTC, jbrauck-unchained commented on apps/coordinator/src/components/App.tsx
> +          variant="permanent"
Done

2025-05-13 00:29 UTC, jbrauck-unchained commented on apps/coordinator/src/components/App.tsx
> +            width: 300,
done

2025-05-13 00:29 UTC, jbrauck-unchained commented on apps/coordinator/src/components/App.tsx
> +            [`& .MuiDrawer-paper`]: { width: 300, boxSizing: "border-box" },
done

2025-05-13 00:29 UTC, jbrauck-unchained commented on apps/coordinator/src/components/App.tsx
> +          marginLeft: location.pathname === "/" ? 0 : `300px`,
done

2025-05-13 00:31 UTC, jbrauck-unchained commented on apps/coordinator/src/components/LandingPage.tsx
> +          <h4 className={classes.footerTitle}>Resources</h4>
done

2025-05-13 02:26 UTC, jbrauck-unchained commented on apps/coordinator/src/components/App.tsx
> +        <Container maxWidth={false} disableGutters sx={{ maxWidth: "100%" }}>
done

2025-05-13 02:37 UTC, jbrauck-unchained commented
Hoping tests pass and we can SNED IT

2025-05-13 15:30 UTC, bucko13 commented on apps/coordinator/src/components/LandingNav.styles.tsx
ooof on all of the `!important`'s

2025-05-13 15:51 UTC, jbrauck-unchained commented on apps/coordinator/src/components/LandingNav.styles.tsx
We talked about this a while back. I couldn't remember why I needed them but I was in some sort of hell with this stuff. I can circle back again and try to remember why

2025-05-14 15:40 UTC, bucko13 approved these changes
Lgtm! (literally)
<img width="1486" alt="Screenshot 2025-05-14 at 10 40 22 AM" src="https://github.com/user-attachments/assets/2662b98a-35c9-4233-842d-1fde5bb1e327" />

2025-05-14 17:59 UTC, merged

2025-05-15 06:19 UTC, Legend101Zz commented
So we finally have it live 🥳