PsbtV2.setProprietaryValue sets 0xFC keytypes for all maps
caravan-bitcoin/caravan pull request #73
Opened 2024-04-17 03:59 UTC by Shadouts

This change adds `PsbtV2.setProprietaryValue()` which can set proprietary values (keytype `0xFC`) for all maps. Map selector and keydata values are specified in the method args, and the final key is formatted as `0xFC<compact uint identifier length><bytes identifier><bytes subkeytype><bytes subkeydata>`

2024-04-30 17:59 UTC, bucko13 requested changes
Looks good! Just needs a changeset

2024-04-30 17:59 UTC, bucko13 commented on packages/caravan-psbt/README.md
> +##### `public setProprietaryValue`
Low priority todo list: it would be nice if we autogenerated docs

2024-05-02 02:47 UTC, Shadouts commented
Changeset added in 33f7ac20c0983dbacf580d775091534ebea770ec

2024-05-02 16:16 UTC, bucko13 approved these changes

2024-05-02 16:16 UTC, merged